import { homedir, platform } from "node:os";
import { join, dirname, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";
import { access } from "node:fs/promises";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Root of the npm package (where assets/ lives) */
export const PACKAGE_ROOT = join(__dirname, "..", "..");

/** Assets directory containing pre-rendered .md files */
export const ASSETS_DIR = join(PACKAGE_ROOT, "assets");

/** Explicit project root override via --project-root flag or env var. */
let projectRootOverride: string | null = null;

export function setProjectRoot(path: string | null): void {
  projectRootOverride = path;
}

/** Walk upward from cwd to find the nearest directory containing .git or package.json. Falls back to cwd. */
export async function findProjectRoot(): Promise<string> {
  if (projectRootOverride) return projectRootOverride;

  const envRoot = process.env["ULUOPS_PROJECT_ROOT"];
  if (envRoot) {
    if (!isAbsolute(envRoot)) {
      throw new Error(`ULUOPS_PROJECT_ROOT must be an absolute path, got: ${envRoot}`);
    }
    if (envRoot.includes("..")) {
      throw new Error(`ULUOPS_PROJECT_ROOT must not contain traversal sequences: ${envRoot}`);
    }
    return envRoot;
  }

  let dir = process.cwd();
  const root = dirname(dir);
  while (dir !== root) {
    if (await isProjectMarker(dir)) return dir;
    dir = dirname(dir);
  }
  if (await isProjectMarker(dir)) return dir;
  return process.cwd();
}

async function isProjectMarker(dir: string): Promise<boolean> {
  try {
    await access(join(dir, ".git"));
    return true;
  } catch {
    // continue
  }
  try {
    await access(join(dir, "package.json"));
    return true;
  } catch {
    // continue
  }
  return false;
}

/** Validate an env-var-supplied path: must be absolute and contain no traversal sequences. */
function validateEnvPath(value: string, varName: string): string {
  if (!isAbsolute(value)) {
    throw new Error(`${varName} must be an absolute path, got: ${value}`);
  }
  if (value.includes("..")) {
    throw new Error(`${varName} must not contain traversal sequences: ${value}`);
  }
  return value;
}

/** Return the Claude config home directory (~/.claude by default, or CLAUDE_HOME env override). */
export function getClaudeHome(): string {
  const envHome = process.env["CLAUDE_HOME"];
  if (envHome) return validateEnvPath(envHome, "CLAUDE_HOME");
  return join(homedir(), ".claude");
}

/** Return the path to Claude's global config file (~/.claude.json by default, or CLAUDE_JSON_PATH env override). */
export function getClaudeJsonPath(): string {
  const envPath = process.env["CLAUDE_JSON_PATH"];
  if (envPath) return validateEnvPath(envPath, "CLAUDE_JSON_PATH");
  return join(homedir(), ".claude.json");
}

/** Return the path to the project-local MCP config file (.mcp.json in project root). */
export async function getLocalMcpPath(): Promise<string> {
  return join(await findProjectRoot(), ".mcp.json");
}

/** Return the UluOps state directory (~/.uluops/). Harness-neutral. */
export function getUluopsDir(): string {
  return join(homedir(), ".uluops");
}

/** Return the path to the UluOps install manifest file (new location). */
export function getManifestPath(): string {
  return join(getUluopsDir(), "manifest.json");
}

/** Return the legacy manifest path for migration. */
export function getLegacyManifestPath(): string {
  return join(getClaudeHome(), "uluops-manifest.json");
}

/**
 * Return the backup directory for a harness's **config** files.
 *
 * Scope is deliberately narrow: this directory holds copies of mutable
 * user-owned config surfaces (the MCP config file, the shell profile),
 * NOT vendor-owned tool files in `~/.claude/tools/agent-metrics/`. Tool
 * files are treated as disposable — they can be regenerated by re-running
 * setup, and the source of truth lives in the npm-installed
 * `@uluops/agent-metrics` package. Backing them up would require a
 * different ritual (versioned snapshots tied to the manifest's
 * hooksInstalledVersion) and is not provided here.
 *
 * Renaming this to `getConfigBackupDir` would be more honest but is a
 * public surface change deferred until we have a tool-file backup to
 * disambiguate against.
 */
export function getBackupDir(harnessName: string): string {
  return join(getUluopsDir(), "backups", harnessName);
}


/** Detect the user's shell and return its name and profile path, or null if unsupported. */
export function getShellProfile(): { shell: string; path: string } | null {
  const shell = process.env["SHELL"] ?? "";
  const home = homedir();
  const os = platform();

  if (shell.endsWith("/zsh")) {
    return { shell: "zsh", path: join(home, ".zshrc") };
  }
  if (shell.endsWith("/bash")) {
    const file = os === "darwin" ? ".bash_profile" : ".bashrc";
    return { shell: "bash", path: join(home, file) };
  }
  if (shell.endsWith("/fish")) {
    return {
      shell: "fish",
      path: join(home, ".config", "fish", "config.fish"),
    };
  }
  return null;
}
